spring.application.name=transshipment-api
spring.datasource.url=jdbc:postgresql://localhost:5432/transshipment_db
spring.datasource.username=postgres
spring.datasource.password=M72AP

spring.jpa.hibernate.ddl-auto=update